### ISSUE TITLE
Images not webpacked

### ISSUE THREAD

**Issue by MaryBartlett** [Aleksion/generator-angular-webpack-babel#1]
I'm not sure if this is just me misusing this project or whether it is an actual problem - but I'm having trouble using images in the project. They don't get copied to the dist folder (and given the below comment inside the karma config I expected they would be).

```
        // ASSET LOADER
        // Reference: https://github.com/webpack/file-loader
        // Copy png, jpg, jpeg, gif, svg, woff, woff2, ttf, eot files to output
        // Rename the file using the asset hash
        // Pass along the updated reference to your code
        // You can add here any file extension you want to get copied to your output
```

I was trying to use the image in CSS as a background image. Could you provide some documentation for how to do this?

**Comment by Aleksion** [comment]
Hi Mary,

I've tweaked quite a few things since I created the generator - based on exactly those kind of issues. I'll try to get the changes into the generator some time tomorrow :)

Are you seeing an actual error, or are they simply not getting copied? 
Because if the latter is the case it might just be that the relative path you're using is wrong? CSS files won't throw an error if the image cannot be found - it will simply just not be displayed.
