### ISSUE TITLE
Views organization

### ISSUE THREAD

**Issue by ArnaudValensi** [Aleksion/generator-angular-webpack-babel#3]
Hi,

I have a little question about how you use this architecture.
Are `features` the views: so each route would go to a different feature?
Or is a feature would be more: the main site, the administration site, etc... In this case do you use nested routes to show the different views?

I know it is more an angular question than an issue, but I'm curious and I like this repo.

Thanks :)

**Comment by Aleksion** [comment]
Hi @ArnaudValensi 

Sorry for taking so long to reply - it slipped my mind.

Yes, that is the intention. Some developers prefer arranging features at the root. Meaning you would get the following structure:

```
- components
- shared
- home
- products
- product
```

instead of:

```
- components
- shared
- features
   - home
   - products
   - product
```

A feature could contain subroutes - I've done that quite a few times. But it can get messy if you nest too much.

Does that make sense to you?

**Comment by ArnaudValensi** [comment]
Yes, perfect. Thank you very much @Aleksion !

**Comment by Aleksion** [comment]
You're welcome :)
